language: node_js
node_js:
  - "node"
install:
  - npm install
  - npm i travis-ci-cloudfront-invalidation --save-dev
before_deploy:
  - gatsby build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET_NAME_BLOG
  region: ap-northeast-1
  skip_cleanup: true
  local_dir: public
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $AWS_CLOUDFRONT_DISTRIBUTION_ID_BLOG -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -o 'master'