language: node_js
node_js:
  - "node"
install:
  - npm install
before_deploy:
  - gatsby build
deploy:
  provider: pages
  local_dir: public
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master